### ISSUE TITLE
/bin/sh: 1: sdk: not found

### ISSUE THREAD

**Issue by devcdcc** [donbeave/docker-sdkman#1]
Hi, i am new docker user, but i don't if that is a issue or dumb user XD
my  **_Dockerfile_** contains the flollwing lines.

```
FROM donbeave/sdkman
RUN sdk list java
```

and this is the response, using that command **_docker build -t test4 ._**
![image](https://user-images.githubusercontent.com/13904437/39663258-f737a4aa-503d-11e8-9501-c4db3091f7a1.png)

```
Step 2/2 : RUN sdk list java
 ---> Running in e14718c7aad6
/bin/sh: 1: sdk: not found
The command '/bin/sh -c sdk list java' returned a non-zero code: 127

```

could you please help me?
Thanks.

**Comment by donbeave** [comment]
@devcdcc you can do this way:

Dockerfile:

```
FROM donbeave/sdkman

ADD test.sh /
RUN chmod a+x /test.sh

CMD /test.sh
```

test.sh:
```
#!/bin/bash

source "$SDKMAN_DIR/bin/sdkman-init.sh"

sdk list java
```

**Comment by n1bor** [comment]
RUN source "$SDKMAN_DIR/bin/sdkman-init.sh" && sdk list java

works too...
